# Generated by Django 3.1.7 on 2021-03-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Student_data_insert',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('RollNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Mail', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher_data_insert',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('Teacher_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Mail', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='enrolled',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_ID', models.ForeignKey(db_column='Course_ID', on_delete=django.db.models.deletion.CASCADE, to='Quiz.course')),
                ('RollNo', models.ForeignKey(db_column='RollNo', on_delete=django.db.models.deletion.CASCADE, to='Quiz.student_data_insert')),
            ],
            options={
                'verbose_name': 'Enrolled Student',
                'db_table': 'enrolled',
            },
        ),
    ]
